"""
YTP-013: Content Performance Analytics
Tracks and analyzes performance of content generated by the YouTube pipeline.
"""
import logging
from typing import Optional, Dict, Any, List
from dataclasses import dataclass, field
from datetime import datetime, timezone
from collections import defaultdict

logger = logging.getLogger(__name__)


@dataclass
class ContentMetrics:
    """Performance metrics for a piece of content."""
    content_id: str
    source_video_id: str
    platform: str
    views: int = 0
    likes: int = 0
    comments: int = 0
    shares: int = 0
    engagement_rate: float = 0.0
    click_through_rate: float = 0.0
    tracked_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class ContentAnalyticsService:
    """
    Tracks content performance across platforms.

    Aggregates metrics from blog posts, social posts, and video clips
    generated by the YouTube pipeline.
    """

    def __init__(self):
        self._metrics: Dict[str, List[ContentMetrics]] = defaultdict(list)

    def track(self, metrics: ContentMetrics) -> None:
        """Record metrics for a content piece."""
        self._metrics[metrics.content_id].append(metrics)
        logger.debug("Tracked metrics for %s on %s", metrics.content_id, metrics.platform)

    def get_metrics(self, content_id: str) -> List[ContentMetrics]:
        """Get all metrics for a content piece."""
        return self._metrics.get(content_id, [])

    def get_aggregate(self, source_video_id: str) -> Dict[str, Any]:
        """
        Get aggregated metrics for all content from a source video.

        Args:
            source_video_id: Original YouTube video ID

        Returns:
            Aggregated metrics across all platforms
        """
        total_views = 0
        total_likes = 0
        total_comments = 0
        total_shares = 0
        platform_metrics: Dict[str, Dict[str, int]] = {}

        for content_id, metrics_list in self._metrics.items():
            for m in metrics_list:
                if m.source_video_id == source_video_id:
                    total_views += m.views
                    total_likes += m.likes
                    total_comments += m.comments
                    total_shares += m.shares

                    if m.platform not in platform_metrics:
                        platform_metrics[m.platform] = {
                            "views": 0, "likes": 0, "comments": 0, "shares": 0
                        }
                    platform_metrics[m.platform]["views"] += m.views
                    platform_metrics[m.platform]["likes"] += m.likes
                    platform_metrics[m.platform]["comments"] += m.comments
                    platform_metrics[m.platform]["shares"] += m.shares

        return {
            "source_video_id": source_video_id,
            "total_views": total_views,
            "total_likes": total_likes,
            "total_comments": total_comments,
            "total_shares": total_shares,
            "total_engagement": total_likes + total_comments + total_shares,
            "platform_breakdown": platform_metrics,
        }

    def get_top_performing(self, limit: int = 10) -> List[Dict[str, Any]]:
        """Get top performing content pieces by engagement."""
        scored = []
        for content_id, metrics_list in self._metrics.items():
            total = sum(m.likes + m.comments + m.shares for m in metrics_list)
            scored.append({
                "content_id": content_id,
                "total_engagement": total,
                "platforms": list(set(m.platform for m in metrics_list)),
            })

        scored.sort(key=lambda x: x["total_engagement"], reverse=True)
        return scored[:limit]

    def get_stats(self) -> Dict[str, Any]:
        """Get overall analytics statistics."""
        total_entries = sum(len(v) for v in self._metrics.values())
        return {
            "total_content_pieces": len(self._metrics),
            "total_metric_entries": total_entries,
            "platforms": list(set(
                m.platform
                for metrics_list in self._metrics.values()
                for m in metrics_list
            )),
        }
