"""
Blotato Account Mapping — READ FROM THE REGISTRY, NOT TYPED HERE.

Maps MediaPoster usernames to Blotato account IDs for posting. The mapping now
comes from the canonical account registry at
``~/Documents/Software/airtime/accounts.json``, which is itself generated by
asking each provider (Google, Meta, Blotato) what its accounts are.

Why this file stopped being a hand-maintained list (2026-08-21)
--------------------------------------------------------------
It used to hold a list copied by hand from the Blotato dashboard, and an audit
against the live ``/v2/users/me/accounts`` endpoint found it wrong in nine
places at once:

    243  listed as tiktok      -> really threads
    4151 listed as twitter     -> really tiktok
    1369 listed as threads     -> really instagram
    4150 listed as threads     -> really tiktok
    571  listed as linkedin    -> really twitter
    201  listed as bluesky     -> really threads (Blotato has no bluesky at all)
    4508 listed on tiktok AND instagram   -> tiktok only
    243  listed on tiktok AND pinterest   -> threads only
    34350 / 41045 / 201        -> missing entirely

and its YouTube channel id read ``UCnDBsELI2OlaEl5yxA77HNA`` where the real
channel is ``UCnDBsELI2OIaEI5yxA77HNA`` — two lowercase ``l`` where a capital
``I`` belongs, indistinguishable by eye. The file's own comments admitted the
doubt ("This might be Threads per memory", "Same ID as TikTok - verify").

Posting to the wrong account is not recoverable by editing a row afterwards: it
is public, on the wrong brand, and deleting it costs whatever reach it had. So
the list is no longer transcribed. If an account is wrong here now, it is wrong
in the registry, and ``airtime/scripts/accounts-build.py --apply`` re-reads it
from the providers.

The public API is unchanged — same dataclass, same functions, same
``USERNAME_TO_BLOTATO_ID`` shape — so callers need no edits.
"""

from typing import Dict, List, Optional
from dataclasses import dataclass
from pathlib import Path
import json
import os

try:
    from loguru import logger
except ImportError:  # keep this module importable without loguru
    import logging

    logger = logging.getLogger(__name__)


REGISTRY_PATH = Path(os.environ.get(
    "AIRTIME_ACCOUNTS_JSON",
    Path.home() / "Documents/Software/airtime/accounts.json"))

# Registry platform vocabulary -> the names MediaPoster and Blotato use.
# These differ for exactly the platforms that also have a first-party
# publisher, which is why the mismatch went unnoticed for so long.
_PLATFORM_OUT = {
    "youtube_shorts": "youtube",
    "instagram_reels": "instagram",
    "facebook_reels": "facebook",
    "x": "twitter",
    "tiktok": "tiktok",
    "threads": "threads",
    "pinterest": "pinterest",
}


@dataclass
class BlotatoAccount:
    """Represents a connected Blotato account"""
    blotato_id: int
    platform: str
    username: str
    display_name: Optional[str] = None
    is_active: bool = True
    registry_id: Optional[str] = None   # the canonical join key


def normalize_username(username: str) -> str:
    """Normalize username for matching.

    NOTE: this deliberately does not strip underscores. ``@the_isaiah_dupree``
    and ``@the_isaiah_dupree_`` are two different real accounts whose entire
    difference is one trailing character, and a normaliser that removes it maps
    posts to the wrong brand.
    """
    return username.lower().strip().lstrip('@').replace(' ', '_')


def _load_registry() -> List[BlotatoAccount]:
    try:
        raw = json.loads(REGISTRY_PATH.read_text())
    except Exception as e:  # noqa: BLE001
        logger.warning(
            f"blotato_accounts: cannot read registry {REGISTRY_PATH}: {e}. "
            f"Returning EMPTY rather than a stale guess — a wrong account id "
            f"publishes to the wrong brand, a missing one just fails loudly.")
        return []

    out: List[BlotatoAccount] = []
    for a in raw.get("accounts") or []:
        # An account reachable through Blotato either publishes via it, or has
        # it as a declared fallback. Both are valid Blotato targets.
        for slot in ("credentials", "fallback"):
            c = a.get(slot) or {}
            if c.get("kind") != "blotato" or not c.get("blotato_account_id"):
                continue
            platform = _PLATFORM_OUT.get(a.get("platform"))
            if not platform:
                continue
            handle = (a.get("handle") or "").lstrip("@")
            out.append(BlotatoAccount(
                blotato_id=int(c["blotato_account_id"]),
                platform=platform,
                username=handle or (a.get("display_name") or ""),
                display_name=a.get("display_name"),
                is_active=bool(a.get("publishable")),
                registry_id=a.get("id"),
            ))
            break
    return out


BLOTATO_ACCOUNTS: List[BlotatoAccount] = _load_registry()


def get_blotato_id(platform: str, username: str) -> Optional[int]:
    """Get Blotato account ID for a given platform and username"""
    account = get_blotato_account(platform, username)
    return account.blotato_id if account else None


def get_blotato_account(platform: str, username: str) -> Optional[BlotatoAccount]:
    """Get the full account record for a platform + username"""
    normalized = normalize_username(username)
    platform_lower = platform.lower()
    for account in BLOTATO_ACCOUNTS:
        if (account.platform.lower() == platform_lower
                and normalize_username(account.username) == normalized):
            return account
    return None


def get_all_accounts_for_platform(platform: str) -> List[BlotatoAccount]:
    platform_lower = platform.lower()
    return [a for a in BLOTATO_ACCOUNTS
            if a.platform.lower() == platform_lower and a.is_active]


def get_account_by_blotato_id(blotato_id: int) -> Optional[BlotatoAccount]:
    for account in BLOTATO_ACCOUNTS:
        if account.blotato_id == int(blotato_id):
            return account
    return None


# Username to Blotato ID mapping (for quick lookups)
USERNAME_TO_BLOTATO_ID: Dict[str, int] = {}
for _account in BLOTATO_ACCOUNTS:
    if _account.blotato_id:
        _key = f"{_account.platform.lower()}:{normalize_username(_account.username)}"
        USERNAME_TO_BLOTATO_ID[_key] = _account.blotato_id


def lookup_blotato_id(platform: str, username: str) -> Optional[int]:
    """Fast lookup of Blotato ID using the mapping dict"""
    key = f"{platform.lower()}:{normalize_username(username)}"
    return USERNAME_TO_BLOTATO_ID.get(key)


if __name__ == "__main__":
    print("=== Blotato Account Mapping (from registry) ===")
    print(f"source: {REGISTRY_PATH}")
    print(f"Total accounts: {len(BLOTATO_ACCOUNTS)}")
    for _a in sorted(BLOTATO_ACCOUNTS, key=lambda x: (x.platform, x.blotato_id)):
        flag = "" if _a.is_active else "  (not publishable)"
        print(f"  {_a.blotato_id:<7} {_a.platform:<11} "
              f"{_a.username:<24} {_a.registry_id}{flag}")
