"""
Matting API Endpoints
=====================
REST API endpoints for video matting service.
"""

import logging
from typing import Optional
from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel, Field

from services.event_bus import EventBus, Topics
from services.matting.models import MattingModel, MattingOperation

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/matting", tags=["matting"])


class MattingConfigRequest(BaseModel):
    """Matting configuration."""
    operation: str = Field(default="extract_person", description="Operation: extract_person, extract_object, remove_background, composite")
    target_description: Optional[str] = Field(default=None, description="Target description (for SAM 2)")
    clean_background_plate: Optional[str] = Field(default=None, description="Path to clean background plate (for BackgroundMattingV2)")
    preserve_alpha: bool = Field(default=True, description="Preserve alpha channel in output")
    downsample_ratio: float = Field(default=0.25, ge=0.1, le=1.0, description="Downsample ratio (0.25 = faster, 1.0 = best quality)")
    device: str = Field(default="auto", description="Device: auto, cuda, cpu")
    model_variant: Optional[str] = Field(default=None, description="Model variant (e.g., mobilenetv3, resnet50 for RVM)")


class MattingRequest(BaseModel):
    """Video matting request."""
    source_video: str = Field(..., description="Path to source video file")
    target_video: Optional[str] = Field(default=None, description="Path to target video (for compositing)")
    model: str = Field(default="rvm", description="Matting model: rvm, mediapipe, background_matting_v2, rembg, sam2")
    config: Optional[MattingConfigRequest] = None
    output_path: Optional[str] = Field(default=None, description="Optional output path")


class MattingResponse(BaseModel):
    """Matting response."""
    job_id: str
    status: str
    message: str
    correlation_id: str


@router.post("/process", response_model=MattingResponse)
async def process_matting(request: MattingRequest, http_request: Request):
    """
    Process video matting (extract person/object with alpha channel).
    
    Publishes a matting.requested event and returns immediately with job_id.
    Use GET /api/matting/status/{job_id} to check status.
    """
    event_bus = EventBus.get_instance()
    
    # Validate model
    try:
        model = MattingModel(request.model)
    except ValueError:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid model: {request.model}. Valid models: {[m.value for m in MattingModel]}"
        )
    
    # Build payload
    payload = {
        "source_video": request.source_video,
        "model": request.model,
    }
    
    if request.target_video:
        payload["target_video"] = request.target_video
    
    if request.output_path:
        payload["output_path"] = request.output_path
    
    if request.config:
        payload["config"] = {
            "operation": request.config.operation,
            "target_description": request.config.target_description,
            "clean_background_plate": request.config.clean_background_plate,
            "preserve_alpha": request.config.preserve_alpha,
            "downsample_ratio": request.config.downsample_ratio,
            "device": request.config.device,
            "model_variant": request.config.model_variant,
        }
    
    # Get correlation ID from request state (set by middleware)
    correlation_id = getattr(http_request.state, "correlation_id", None)
    if correlation_id:
        payload["correlation_id"] = correlation_id
    
    # Publish event
    event_id = await event_bus.publish(
        topic=Topics.MATTING_REQUESTED,
        payload=payload,
        correlation_id=correlation_id,
        source="api"
    )
    
    # Extract job_id from payload (will be generated by MattingRequest)
    job_id = payload.get("job_id", event_id)
    
    logger.info(f"Matting requested: job_id={job_id}, model={request.model}, operation={request.config.operation if request.config else 'extract_person'}")
    
    return MattingResponse(
        job_id=job_id,
        status="queued",
        message="Matting job queued",
        correlation_id=correlation_id or event_id
    )


@router.get("/status/{job_id}")
async def get_matting_status(job_id: str):
    """
    Get status of a matting job.
    
    Note: This requires the matting worker to be running and tracking jobs.
    In production, job status would be stored in a database.
    """
    # TODO: Implement job status lookup from database or worker
    return {
        "job_id": job_id,
        "status": "unknown",
        "message": "Job status lookup not yet implemented. Check event bus for completion events."
    }


@router.get("/models")
async def list_models():
    """List available matting models."""
    return {
        "models": [
            {
                "id": model.value,
                "name": model.name,
                "description": _get_model_description(model)
            }
            for model in MattingModel
        ]
    }


def _get_model_description(model: MattingModel) -> str:
    """Get description for model."""
    descriptions = {
        MattingModel.RVM: "Robust Video Matting - Highest quality, temporal memory, real-time capable",
        MattingModel.MEDIAPIPE: "MediaPipe Selfie Segmentation - Fast, lightweight, works on CPU",
        MattingModel.BACKGROUND_MATTING_V2: "BackgroundMattingV2 - Best with clean background plate",
        MattingModel.REMBG: "rembg - Simple batch processing, good for images",
        MattingModel.SAM2: "SAM 2 - Advanced segmentation, specific objects",
    }
    return descriptions.get(model, f"{model.value} matting model")

