"""
TTS API Endpoints
=================
REST API endpoints for text-to-speech service.
"""

import logging
from typing import Optional
from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel, Field

from services.event_bus import EventBus, Topics
from services.tts.models import TTSModel, EmotionMethod

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/tts", tags=["tts"])


class EmotionConfigRequest(BaseModel):
    """Emotion configuration for TTS."""
    method: str = Field(default="natural", description="Emotion method: natural, reference, vectors, text")
    vectors: Optional[dict] = Field(default=None, description="Emotion vectors (e.g., {'happy': 0.8})")
    weight: float = Field(default=0.8, ge=0.0, le=1.0, description="Emotion weight")
    reference_audio: Optional[str] = Field(default=None, description="Path to emotion reference audio")
    text: str = Field(default="", description="Text description of emotion")


class TTSGenerateRequest(BaseModel):
    """TTS generation request."""
    text: str = Field(..., description="Text to synthesize")
    model: str = Field(default="indextts2", description="TTS model to use")
    voice_reference: str = Field(..., description="Path to voice reference audio file")
    emotion: Optional[EmotionConfigRequest] = None
    output_format: str = Field(default="wav", description="Output format: wav, mp3")
    sample_rate: int = Field(default=22050, description="Sample rate")
    output_path: Optional[str] = Field(default=None, description="Optional output path")


class TTSGenerateResponse(BaseModel):
    """TTS generation response."""
    job_id: str
    status: str
    message: str
    correlation_id: str


@router.post("/generate", response_model=TTSGenerateResponse)
async def generate_tts(request: TTSGenerateRequest, http_request: Request):
    """
    Generate text-to-speech audio.
    
    Publishes a tts.requested event and returns immediately with job_id.
    Use GET /api/tts/status/{job_id} to check status.
    """
    event_bus = EventBus.get_instance()
    
    # Validate model
    try:
        model = TTSModel(request.model)
    except ValueError:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid model: {request.model}. Valid models: {[m.value for m in TTSModel]}"
        )
    
    # Build payload
    payload = {
        "text": request.text,
        "model": request.model,
        "voice_reference": request.voice_reference,
        "output_format": request.output_format,
        "sample_rate": request.sample_rate,
    }
    
    if request.output_path:
        payload["output_path"] = request.output_path
    
    if request.emotion:
        payload["emotion"] = {
            "method": request.emotion.method,
            "vectors": request.emotion.vectors,
            "weight": request.emotion.weight,
            "reference_audio": request.emotion.reference_audio,
            "text": request.emotion.text,
        }
    
    # Get correlation ID from request state (set by middleware)
    correlation_id = getattr(http_request.state, "correlation_id", None)
    if correlation_id:
        payload["correlation_id"] = correlation_id
    
    # Publish event
    event_id = await event_bus.publish(
        topic=Topics.TTS_REQUESTED,
        payload=payload,
        correlation_id=correlation_id,
        source="api"
    )
    
    # Extract job_id from payload (will be generated by TTSRequest)
    # For now, use event_id as job_id
    job_id = payload.get("job_id", event_id)
    
    logger.info(f"TTS generation requested: job_id={job_id}, model={request.model}")
    
    return TTSGenerateResponse(
        job_id=job_id,
        status="queued",
        message="TTS generation job queued",
        correlation_id=correlation_id or event_id
    )


@router.get("/status/{job_id}")
async def get_tts_status(job_id: str):
    """
    Get status of a TTS generation job.
    
    Note: This requires the TTS worker to be running and tracking jobs.
    In production, job status would be stored in a database.
    """
    # TODO: Implement job status lookup from database or worker
    # For now, return a placeholder
    return {
        "job_id": job_id,
        "status": "unknown",
        "message": "Job status lookup not yet implemented. Check event bus for completion events."
    }


@router.get("/models")
async def list_models():
    """List available TTS models."""
    return {
        "models": [
            {
                "id": model.value,
                "name": model.name,
                "description": f"{model.value} TTS model"
            }
            for model in TTSModel
        ]
    }

